apiVersion: v1
kind: Service
metadata:
  name: inference-api
  namespace: predictive-maintenance
  labels:
    app.kubernetes.io/name: inference-api
    app.kubernetes.io/part-of: predictive-maintenance
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: inference-api
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: predictive-maintenance
  labels:
    app.kubernetes.io/name: minio-bridge
    app.kubernetes.io/part-of: predictive-maintenance
spec:
  type: ExternalName
  externalName: host.docker.internal
