apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: predictive-maintenance
resources:
  - namespace.yaml
  - configmap.yaml
  - inference-deployment.yaml
  - inference-service.yaml
  - stream-consumer-deployment.yaml
  - hpa.yaml
